### ISSUE TITLE
Doesn't work: There are no frames to convert

### ISSUE THREAD

**Issue by thvi** [maxmartynov/figma-plugin-frames-to-groups#10]
Hello,
https://1drv.ms/u/s!Aj16T_Ds0bkv3CvTZD3OLt8xYmRL
Bests,
Thierry

**Comment by maxmartynov** [comment]
Hi @thvi ! Thank you for the record.

You can test the plugin with the following example.
1. Create nested elements: `Frame 1 -> Frame 2 -> Rectangle`.
2. Select the `Frame 1`
3. Run the plugin

You will see it will turn `Frame 2` to a new group.

This is the behaviour that was requested by a designer I worked with. How do you expect the plugin should work? Perhaps I'll add a new mode for the plugin.

As from your exampe. Do you want the plugin to make a group from the `Frame 1` or remove it because it's empty? (Currently, the plugin removes empty frames while converting them to groups)

**Comment by thvi** [comment]
Hi,

I want just convert the frame to group and preserve the background content. In this example, I want to preserver the white rectangle.
https://1drv.ms/u/s!Aj16T_Ds0bkv3CzX8spd4MVanknv

Bests

**Comment by maxmartynov** [comment]
I've added the Settings window that manages the default behavior of the plugin. That should fix the problem

https://www.figma.com/community/plugin/848551444907255153/Frames-to-Groups?comment=1206663101810610663

Feature commit: https://github.com/maxmartynov/figma-plugin-frames-to-groups/commit/19e275bcf7e15a32ee047bc6fe2ab4e5011ded62
